FROM ubuntu:18.04@sha256:5f4bdc3467537cbbe563e80db2c3ec95d548a9145d64453b06939c4592d67b6d

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apt-get update -q && \
    apt-get install -qy \
        git=1:2.17.1-1ubuntu0.5 \
        make=4.1-9.1ubuntu1 \
        autotools-dev=20180224.1 \
        autoconf=2.69-11 \
        libtool=2.4.6-2 \
        libssl-dev=1.1.1-1ubuntu2.1~18.04.5 \
        libboost-all-dev=1.65.1.0ubuntu1 \
        libevent-dev=2.1.8-stable-4build1 \
        libdb++-dev=1:5.3.21~exp1ubuntu2 \
        libdb-dev=1:5.3.21~exp1ubuntu2 \
        nano=2.9.3-2 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

RUN cd /opt && \
    git clone https://github.com/fairchainsx/faircoin-2.git

RUN cd /opt/faircoin-2 && ./autogen.sh && \
    ./configure --disable-tests --disable-bench --disable-wallet && \
    make

RUN mkdir /root/.faircoin2 && \
    echo -e "rpcconnect=127.0.0.1\nrpcport=8332\nrpcuser=faircoin\nrpcpassword=mypassword\ntxindex=1" > /root/.faircoin2/faircoin.conf

RUN cd /opt/faircoin-2/src && \
    ./faircoind -daemon -reindex && \
    sleep 60 && \
    ./faircoin-cli stop && \
    sleep 10
